name: Pulumi Maintenance
on:
    push:
        branches: [main]
    pull_request:

jobs:
    public_stack:
        name: Update public stack config
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: update public config
              uses: mikefarah/yq@master
              with:
                  cmd: yq  -i '.config = load("Pulumi.cape-cod-dev.yaml").config | (.. | select(length == 1 and has("secure"))) |= "SET_SECRET"' Pulumi.cape-cod-public.yaml
            - name: create pull request
              if: ${{ github.event_name == 'push' }}
              uses: peter-evans/create-pull-request@v6
              with:
                  commit-message: "chore: update public pulumi stack config"
                  title: Update public pulumi stack configuration
                  body: Changes were detected to the dev stack config, so this updates the public stack config with all secrets removed
                  branch: pulumi-ci-update-public-stack
                  delete-branch: true
